### PR TITLE
Main content

### PR DESCRIPTION
**Pull request by lekegitrepo**

### CODE REVIEW

**Comment by thsvr** [comment]
Hi, 

Can you please check our project and give feedback to us? 

We also are having some problems with these 3 errors (see the print below). Do you know how can we fix it?

Thank you in advance :) 

Cheers,

Temitayo and Thaís.

Captura de tela de 2019-08-28 18-13-48

**Review by stratospherique — COMMENTED** [review]
### Pull request under the review by Ahmed Mahfoudh

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work Team :clap: :clap: . Your page looks perfect :1st_place_medal: . However, You should work more on adding more classes to the framework to get the most of this project. I recommend implementing classes for the requirements below :arrow_down: and add them to a framework stylesheet file:

### Box utilities

#### Margins

* [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [x] The margins should span from `0 rem` to `1 rem`
* [x] The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

* [x] The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
* [x] The padding should span from `0 rem` to `1 rem`
* [x] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

* [x] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [x] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

* [x] A class to set the display property of an element to flex
* [x] A class to set the display property to hidden
* [x] A class to set the display property to none
* [x] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [x] Classes to set vertical alignment as top, bottom or center
* [x] Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

* [x] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [x] Classes to horizontally align text to the left, right or center
* [x] At least five classes to set the font size of an element
* [x] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [x] The CSS files define separate classes for border top, bottom, left, right, all border
* [x] The border should span from 0 to 1rem
* [x] The border should have classes for making box round
* [x] The border should have a class defined to transform a box into a circle

### General notes:

- Regarding the linting problems, you are using css linting on scss linting. `stylelint.config.js` file is configured for css files. Check this [link](https://stylelint.io/), it covers the issue.

### And that's it guys :relieved: . Your project is perfect but it needs implementing the above :nerd_face: . When finished, kindly submit another code review request. Keep up the good work :muscle: :muscle: .

**Comment by thsvr** [comment]
Hi,

Thank you for the feedback :) We did everything you suggested. So, can you please check it again and tell us if it can be approved?

We also need some professional help to fix the previous problem (with sass errors) that linter complains about and we couldn't figure out how to fix it. 

Thank you in advance!

Cheers,

Temitayo and Thaís.

**Comment by Oghenebrume50** [comment]
Reviewing......

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi, guys, everything looks good, the only thing that is left now is to correct linting errors, please do this and submit for re-review :+1:

**Comment by samgaco** [comment]
#### The linter errors are corrected hence the project is approved :+1:  Congratulations on finishing this part of the course! and on your project too, looks great :medal_sports: 

Keep up with the good work moving forward :100:

**Pull request merged**
